screwdriver-cd/workflow-parser

index.js
lib/hasCycle.js
lib/hasJoin.js
test/lib/hasCycle.test.js
test/lib/hasJoin.test.js

- Add a hasJoin to check if there is a join in edges
- fix `hasCycle` to return `false` when there is a `join` but no cycle (the `join` node will be visited twice but it is not a cycle)
Related to https://github.com/screwdriver-cd/screwdriver/issues/770

feat: add hasJoin function and fix hasCycle

---

lib/getWorkflow.js
test/data/expected-external.json
test/data/requires-workflow-exttrigger.json
test/lib/getWorkflow.test.js

Context:
========
I want my pipeline to build when another pipeline(job) completes successfully
I want to be able to have my job "C" run when job "A" or job "B" finishes successfully
Objective:
----------
Workflow parser adds edges and nodes for external pipeline triggers, e.g. `~sd@1234:foo` matching pipeline `1234` job `foo`
Workflow parser accepts a requires job config with a tilde, e.g. `~A` to match job `A` but will not be considered as part of a join operation.
Links:
-----
https://github.com/screwdriver-cd/screwdriver/issues/770

feat(770): support external pipelines as nodes, logical OR

---

index.js
lib/getSrcForJoin.js
test/data/join-workflow.json
test/lib/getSrcForJoin.test.js

- add `getSrcForJoin` function
We will use this helper function to do join trigger in API.
Related to https://github.com/screwdriver-cd/screwdriver/issues/700

feat: add getSrcForJoin function

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

To trigger from specific branch commit, getNextJobs allow regex when check edge.src and config.trigger.
Use edge.src as a regex and check the trigger does match the regex or not.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1082

feat(1082):[5] Check the trigger does match the regex or not

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

The branch specific trigger for `~pr` is not implemented yet.
* Fix trigger checking logic for branch  specific `~pr` jobs
* [workflow design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#branch-filtering-scm-branch-specific-jobs)
* issue https://github.com/screwdriver-cd/screwdriver/issues/1082

feat(1082): [13] [small] fix to enable branch specific pr trigger

---

lib/getNextJobs.js
package.json
screwdriver.yaml
test/lib/getNextJobs.test.js

We want to implement `prChain` feature. If `prChain` is true, a job name does not have `PR-` prefix. 
This PR enables to use `prChain` in `getNextJobs()`.
This PR also update node version to 8 from 6.
This change may have backward compatibility.
Related Issue: https://github.com/screwdriver-cd/screwdriver/issues/1010
Related PRs:
- https://github.com/screwdriver-cd/data-schema/pull/296
- https://github.com/screwdriver-cd/config-parser/pull/81

[3] feat(1010): enable to use prChain on getNextJobs()

---

lib/getNextJobs.js
package.json
test/lib/getNextJobs.test.js

This PR is the second step of enabling prChain feature.
This time we fixed only a backend（api, models, workflow-graph）. UI will be fixed next time.
- If `prChain` flag is true in screwdriver.yaml, run subsequent jobs following workflow graph.
- Create all jobs with `PR-${prNum}:` prefix.
https://github.com/screwdriver-cd/screwdriver/pull/1444
https://github.com/screwdriver-cd/models/pull/315
- New design of prChain feature
https://github.com/screwdriver-cd/screwdriver/issues/1010#issuecomment-448142968

feat(1010): [1] enabling prChain 2nd step

---

lib/getNextJobs.js
lib/getWorkflow.js
package.json
test/data/expected-external.json
test/data/expected-output.json
test/data/requires-workflow-exttrigger.json
test/data/requires-workflow.json
test/lib/getNextJobs.test.js
test/lib/getWorkflow.test.js

To implement `~release` and `~tag` trigger, this PR adds these trigger as a special trigger and a node.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/823
- data-schema: https://github.com/screwdriver-cd/data-schema/pull/320

feat(823): [2] add ~release and ~tag as special trigger

---

lib/getWorkflow.js
test/data/expected-external.json
test/data/expected-output.json
test/data/requires-workflow-exttrigger.json
test/lib/getWorkflow.test.js

This PR fixes https://github.com/screwdriver-cd/workflow-parser/pull/18#issuecomment-470328721 
> we shouldn't add ~tag and ~release to the default nodes. We should only add those if user configure it in the requires. Otherwise those will always show up in the UI.
Related: https://github.com/screwdriver-cd/screwdriver/issues/823

feat(823): not to add ~release and ~tag node as a default node

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

Now there are orthographical variants like 'prChain' and 'chainPR' .
We want to unify these to `chainPR`.
Add `chainPR` setter/getter method to pipeline model in order to convert the `prChain` to `chainPR`.
We don't change `prChain` property itself because it is already used in data-schema and it takes too much cost to change this.
https://github.com/screwdriver-cd/data-schema/pull/330
https://github.com/screwdriver-cd/models/pull/371
https://github.com/screwdriver-cd/screwdriver/pull/1593

fix: [2] convert prChain to chainPR

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

We want to use PR environment variables  in a build which is triggered by branch specific pr trigger.
https://github.com/screwdriver-cd/screwdriver/issues/1537
To fix this problem, we should treat pr trigger event and branch specific pr trigger event the same.
Add `PR-$num:` to job name when trigger is branch specific pr.
https://github.com/screwdriver-cd/screwdriver/issues/1537
https://github.com/screwdriver-cd/screwdriver/pull/1594

fix(1537): [1] Fix ~pr trigger and ~pr:branch trigger have the same behavior

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

Reverts screwdriver-cd/workflow-parser#22
This is breaking a test in model: https://cd.screwdriver.cd/pipelines/9/builds/113610/steps/test
Need to push out a change in the model, so need to revert this change.
Please feel free to reopen/remerge once figure out the issue.

fix: Revert "fix(1537): [1] Fix ~pr trigger and ~pr:branch trigger have the same behavior"

---

lib/getNextJobs.js
test/lib/getNextJobs.test.js

Reverts screwdriver-cd/workflow-parser#23
I fixed test in the models.
https://github.com/screwdriver-cd/models/pull/382
Therefore, I reopen the same PR #22
https://github.com/screwdriver-cd/workflow-parser/pull/22
https://github.com/screwdriver-cd/screwdriver/pull/1594
https://github.com/screwdriver-cd/screwdriver/pull/1537
https://github.com/screwdriver-cd/models/pull/382

Revert "fix: Revert "fix(1537): [1] Fix ~pr trigger and ~pr:branch trigger have the same behavior""

---

lib/getSrcForJoin.js
package.json
test/lib/getSrcForJoin.test.js

Join job does not work when chainPR workflow.
PR jobs have `PR-{num}:` prefix, so jobs will not be found in `workflowGraph.edges.dest` objects.
- We need to trim `PR-{num}:` prefix when searching jobs from workflowGraph objects in chainPR workflow.
- When returning join jobs, we need to add `PR-{num}:` prefix again.
- Other PRs
API: https://github.com/screwdriver-cd/screwdriver/pull/1697
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix: [1]Join job does not work when chainPR workflow

---

lib/getWorkflow.js
test/data/expected-output.json
test/data/requires-workflow.json

Screwdriver currently handles "requires" job names that start with `~pr`, `~commit`, etc. as if they are special root nodes. 
This PR changes the regex in the node name filter to make it match more specifically for `~pr:*` or `~pr` exactly.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1417

fix(1417): Make node name filter more specific

---

lib/getWorkflow.js
package.json
test/data/expected-external-complex.json
test/data/expected-external.json
test/data/requires-workflow-exttrigger.json
test/lib/getNextJobs.test.js
test/lib/getSrcForJoin.test.js
test/lib/getWorkflow.test.js
test/lib/hasCycle.test.js
testworkflow.js

Related: https://github.com/screwdriver-cd/screwdriver/issues/1710
Blocked by: https://github.com/screwdriver-cd/config-parser/pull/94
Previously, we only include nodes & edges from the workflow graph. This PR will generate external nodes & external edges that are downstream for each job.

feat(1710): support external join. BREAKING CHANGE: add new external join logic [4]

---

lib/getWorkflow.js
test/data/expected-external-complex.json
test/lib/getNextJobs.test.js

Need to make sure we don't store ~ for external pipeline in workflow as a dest.
This PR does not store ~ for dest.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710

fix(1710): Do not store ~ for external pipeline dest [1]

---

lib/getNextJobs.js
test/data/external-join.json
test/lib/getNextJobs.test.js

currently workflow-parser returns remote job for pr event when both external join and chainPR are turned on, which breaks pr event
do not return remote job for pr event
https://github.com/screwdriver-cd/screwdriver/issues/1973

fix(1973): don't return remote job for pr event

---

lib/getWorkflow.js
test/data/expected-external-join.json
test/lib/getNextJobs.test.js
test/lib/getWorkflow.test.js

currently workflow can have duplicate remote jobs, one with ~ and one without
duplicate remote job should not exist
https://github.com/screwdriver-cd/screwdriver/issues/1968

fix(1968): remove ~ for downstream external job

---

package.json
screwdriver.yaml

Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR upgrades to node:12
https://github.com/screwdriver-cd/screwdriver/issues/1958

feat(1958): hapi v19 upgrade, node:12. BREAKING CHANGE: data-schema v20

---

package.json

Seeing `Error: Cannot find module './node_modules/semantic-release/src/lib/plugin-noop.js'`]
https://cd.screwdriver.cd/pipelines/529/builds/764489/steps/publish
This PR removes old package.json section for noop plugin.
Related to https://github.com/screwdriver-cd/executor-base/pull/76

fix: Remove noop for semantic release

---

lib/getWorkflow.js
test/lib/getWorkflow.test.js

Node of stage represents a job and has `id` and `name` attributes.
Add a reference to the stage in wokflowGraph nodes which would help us to filter/group nodes by stage name.
Ex: https://github.com/screwdriver-cd/screwdriver/pull/2933/files#diff-e01d96efa0729764af51697e9dd42865efba14cb4562ebcb4207cb75528b4ffcR843
https://github.com/screwdriver-cd/screwdriver/issues/2767
https://github.com/screwdriver-cd/data-schema/pull/530

feat(2767): Add reference to stage in workflowGraph nodes

---

lib/getWorkflow.js
test/data/expected-external-complex.json
test/data/expected-external-join.json
test/data/expected-external.json
test/data/expected-output.json
test/lib/getSrcForJoin.test.js
test/lib/getWorkflow.test.js

When the following settings are made, the `join` job does not run upon restarting the build from `main`. This is due to the fact that when a Remote Join is composed of only one job, it is not treated as a Remote Join and it is also not triggered as `~sd@456:sub`.
```yaml
jobs:
main:
requires: [ ~commit ]
join:
requires: [ sd@456:sub ]
jobs:
sub:
requires: [ ~sd@123:main ]
```
This PR will make a correction to treat it as a join condition even if it consists of only one job.
Once it is treated as a Remote Join, it will no longer be excluded at the part below during restart, allowing the build to run correctly.
https://github.com/screwdriver-cd/screwdriver/blob/c1f15b7647dc4360093e9df64d9db69131718640/plugins/builds/index.js#L1009
I confirm that this contribution is made under the terms of …

fix: let one job require be join

---

lib/getWorkflow.js
test/data/expected-external-complex.json
test/data/expected-external-join.json
test/data/expected-external.json
test/data/expected-output.json
test/lib/getSrcForJoin.test.js
test/lib/getWorkflow.test.js

This reverts commit b5e450902914864ebae466303c1deb88da5fb2c1.
If a Remote Triggered downstream pipeline was Remote Triggered twice, only one job would be triggered.
Reference: https://github.com/screwdriver-cd/screwdriver/issues/2980.
Due to this issue, https://github.com/screwdriver-cd/workflow-parser/pull/45 was reverted.
I would like to change the https://github.com/screwdriver-cd/workflow-parser/pull/45 again with this issue resolved.
This PR is only a Revt of Revt.
Corrections to resolve the problem will be made in https://github.com/screwdriver-cd/screwdriver/pull/3008.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its …

fix(2980): Revert "Revert "fix: let one job require be join" (#46)" [1]

---

lib/getWorkflow.js
test/lib/getWorkflow.test.js

`stageName` is not being set for workflow graph `node` that is associated with a `stage` when `triggerFactory` is not available.
`stageName` for workflow graph `node` that is associated with a `stage` should always be set irrespective of the availability of `triggerFactory`.
https://github.com/screwdriver-cd/screwdriver/issues/3041

feat(3014): Process and include stage info in the workflow graph nodes when triggerFactory is not available

---

lib/getWorkflow.js
package.json
test/lib/getWorkflow.test.js

Workflow graph node (Ex: implicit setup/teardown job of a stage) for an event is identified as virtual based on the presence/value of `screwdriver.cd/virtualJob` annotation in the corresponding job definition.
Since the job definition reflects the latest configuration from `screwdriver.yaml`, referring to current annotations of the job may not be reliable to identify it as virtual for an event.
We need a way to preserve whether the job is virtual or not when event is created.
Add a new attribute `virtual` in the workflow graph `node` to indicate whether it is virtual or not.
https://github.com/screwdriver-cd/screwdriver/issues/3022
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the …

feat(3022): Mark workflow node as virtual if it corresponds to a virtual job

---

lib/getNextJobs.js
test/data/expected-output.json
test/data/requires-workflow.json
test/lib/getNextJobs.test.js

Currently, getNextJobs returns the next job in workflow graph after the stage setup, regardless of the startFrom being in the middle of that stage or not
Return the startFrom job as the next job to execute if the current job is a stage setup and startFrom job is a non setup job in that stage
https://github.com/screwdriver-cd/screwdriver/issues/3143

fix(3413): skip jobs between stage setup and startFrom stage job only if they belong to the same stage

---

package.json

BREAKING CHANGE: Move workflowGraph out of config and keep it at the same level as config
Changes were made in https://github.com/screwdriver-cd/data-schema/pull/571 (and related PRs) to store `workflowGraph` of pipeline template as part of the `config` 
Move `workflowGraph` out of `config` and keep it at the same level as `config`
https://github.com/screwdriver-cd/screwdriver/issues/3171

feat(3171): Pull in latest data-schema to persist pipeline template workflowGraph in a new column

---

lib/getSrcForJoin.js
test/lib/getSrcForJoin.test.js

Currently, job name with `:`  is considered a PR job. So `stage@sandbox:teardown` is being treated as a PR job. To find the source nodes for join, edges are matched with only "teardown" in the dest, causing stage teardown to run prematurely.
This PR uses data-schema regex to filter for PR jobs.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3176

fix(3176): Use data-schema regex to filter for PR jobs
